### ISSUE TITLE
JSON Proxy is returning 404s for /latest

### ISSUE THREAD

**Issue by snowyfox** [domoritz/himawari-8-chrome#255] opened 2020-11-10 19:52 UTC
The extension has been unable to load new data for the last couple of months due to the JSON proxy (https://himawari-8.appspot.com/latest) returning a 404. I bypassed the proxy in a local copy of the extension code in the `getLatestHimawariDate` function to use `https://himawari8-dl.nict.go.jp/himawari8/img/D531106/latest.json` instead, and I'm now able to get images to load again. 

Original Error thrown in the extension: 
`Unexpected token < in JSON at position 0`

Response received from the JSON Proxy:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /himawari8/img/D531106/latest.json was not found on this server.</p>
</body></html>
```

**Comment by domoritz** [comment] 2020-11-10 19:59
Hmm. That may be because the server returned a 404. Let me clear the caches so we refetch. 

The issue is that https://himawari8-dl.nict.go.jp/ doesn't allow cross origin requests so we need the proxy.

**Comment by domoritz** [comment] 2020-11-10 20:05
Ahh, the http endpoint return 404 now. Need to switch to https.

**Comment by snowyfox** [comment] 2020-11-10 20:06
You beat me to it! I was writing up a comment already to say exactly that! Sounds like an easy fix at least.

**Comment by domoritz** [comment] 2020-11-10 20:11
The hardest part is getting google cloud deployment working again since I haven't deployed in a while.

**Comment by domoritz** [comment] 2020-11-10 20:22
Works again at https://himawari-8.appspot.com/latest. Thanks for the issue report @snowyfox!

**Comment by domoritz** [comment] 2020-11-10 20:23
Fixed in https://github.com/domoritz/himawari-8-chrome/commit/5b2c06981a930ec330aa9faebcb38376661b3907

**Comment by snowyfox** [comment] 2020-11-10 20:23
Glad I could help you solve the issue :)

I'm not sure if its an artifact of running the extension locally in chrome as an `Unpacked Extension`, but I'm not getting any CORS warnings or errors at all when fetching the `latest.json` data directly from the source. May be worth looking into whether CORS is still an issue now or not sometime.

**Closed as completed by domoritz** 2020-11-10 20:23 UTC

**Comment by snowyfox** [comment] 2020-11-10 20:24
I just re-enabled the original extension that was installed via the web store, and it just updated itself with new images. Issue definitely looks resolved now :)

**Comment by domoritz** [comment] 2020-11-10 20:26
Hmm, they may have fixed things over the last years. It would be nice to remove the need for the proxy. Besides the extension, I also want to make sure that the web page itself works.

Would you want to send a pull request? I can review and make a release.

**Comment by snowyfox** [comment] 2020-11-10 20:30
I may be able to put something together later, but don't have the time right now, so feel free to try it yourself if you've got the time to play around with it
